### PR TITLE
fix few credo issues

### PR DESCRIPTION
**Pull request by fusillicode**
Hi, thank you very much for this wonderful library! 🤗 

I stumbled upon it while browsing the elixirforum and I felt the urge to contribute in some ways.

Despite my still limited understanding of the library code I tried to address some Credo issues that I found by running Credo in `strict` mode.

I'm totally open to the PR rejection as I know that these kind of stuff are somehow debatable and are not bringing any consistent value to the project itself.

Moreover I see that there is already a red spec before my modifications but I didn't add the time to dive in and fixed it. If you want I can try to work on it and include the fix in this PR as soon as I can.

Anyway I remain at your disposal for everything.

Thank you again!

P.S: I really hope to be able to contribute to something more useful in the future!

### CODE REVIEW

**Comment by aseigo** [comment]
Thanks for the fixes! Very much appreciated. 

The code is indeed a bit messier than I would like due to its rather early and rough development state. (And your PR reminds me I need to write some unit tests for AuthPipe.Stage.EctoPassword!)

Looking forward to future PR's .. if you have any ideas or questions, feel free to reach me either here on github or on the Elixir Forums. Cheers!

**Review by aseigo — APPROVED** [review]

**Comment by fusillicode** [comment]
I'm the one who should be thankful to you for your ideas, this library and your commitment to OSS! 😄

Regarding the code I don't find it the messy at all! I just need to get accustomed to it.
I'll try to work on the tests ASAP  😉

Cheers and thanks again! 🤗 🍻

**Comment by aseigo** [comment]
BTW: I just pushed a small fix to address a test I broke yesterday ... so if you dive into tests, you should update your repo first so that the tests that are there all pass again.

**Comment by fusillicode** [comment]
😉👍

**Pull request merged**
